(jde-project-file-version "1.0")
(jde-set-variables
 ;; you can define many JDKs and choose one for each project
 '(jde-compile-option-target (quote ("1.7.0")))
 ;; What should be put as java file header
 '(jde-gen-buffer-boilerplate
   (quote
    ("/*"
     " * Geotools - OpenSource mapping toolkit"
     " * http://www.zhongsou.com/"
     " * (C) 2012, Geotools Project Managment Committee (PMC)"
     " *"
     " * This library is free software; you can redistribute it and/or"
     " * modify it under the terms of the GNU Lesser General Public"
     " * License as published by the Free Software Foundation;"
     " * version 2.1 of the License."
     " *"
     " * This library is distributed in the hope that it will be useful,"
     " * but WITHOUT ANY WARRANTY; without even the implied warranty of"
     " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU"
     " * Lesser General Public License for more details."
     " *"
     " */")))
 ;; You can define many JDKs and choose one for each project
 '(jde-compile-option-target (quote ("1.7")))
 ;; For syntax highlighting and basic syntax checking parse buffer
 ;; number of seconds from the time you changed the buffer.
 '(jde-auto-parse-buffer-interval 600)
 '(jde-enable-abbrev-mode t)
 '(jde-compile-option-directory "./target/classes")
 '(jde-run-working-directory "$HOME/development/incload/src/main/java")
 '(jde-ant-working-directory "./")
 ;; Path to source files for automatic loading
 '(jde-sourcepath '("./src/test/java/"
                    "./src/main/java/"
                    "/opt/java/src/"
                    "/home/arch/inuse/hadoop/src/core/"
                    "/home/arch/inuse/hadoop/src/hdfs/"
                    "/home/arch/inuse/hadoop/src/mapred/"
                    "/home/arch/software/java/junit/hamcrest/src"
                    "/home/arch/inuse/hbase/src/main/java/"))
 '(jde-global-classpath '("./target/classes"
                          "./target/test-classes"
			  "/opt/java/lib/tools.jar"
                          "/home/arch/.m2/repository/junit/junit/4.10/junit-4.10.jar"
                          "/home/arch/development/incload/lib/hamcrest-all-1.3.jar"
                          "/home/arch/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar"
                          "/home/arch/development/incload/lib/commons-cli-1.2.jar"
                          "./lib/activation-1.1.jar"
                          "./lib/asm-3.1.jar"
                          "./lib/avro-1.5.3.jar"
                          "./lib/avro-ipc-1.5.3.jar"
                          "./lib/bcmail-jdk14-136.jar"
                          "./lib/bcprov-jdk14-136.jar"
                          "./lib/commons-beanutils-1.7.0.jar"
                          "./lib/commons-beanutils-core-1.8.0.jar"
                          "./lib/commons-cli-1.2.jar"
                          "./lib/commons-codec-1.4.jar"
                          "./lib/commons-collections-3.2.1.jar"
                          "./lib/commons-configuration-1.6.jar"
                          "./lib/commons-digester-1.8.jar"
                          "./lib/commons-el-1.0.jar"
                          "./lib/commons-httpclient-3.1.jar"
                          "./lib/commons-io-2.1.jar"
                          "./lib/commons-lang-2.5.jar"
                          "./lib/commons-lang-2.5-javadoc.jar"
                          "./lib/commons-lang-2.5-sources.jar"
                          "./lib/commons-logging-1.1.1.jar"
                          "./lib/commons-math-2.1.jar"
                          "./lib/commons-net-1.4.1.jar"
                          "./lib/core-3.1.1.jar"
                          "./lib/dom4j-1.6.1.jar"
                          "./lib/fontbox-0.1.0.jar"
                          "./lib/geronimo-stax-api_1.0_spec-1.0.jar"
                          "./lib/guava-11.0.2.jar"
                          "./lib/guava-11.0.2-javadoc.jar"
                          "./lib/guava-11.0.2-sources.jar"
                          "./lib/guava-bootstrap-11.0.2.jar"
                          "./lib/hadoop-core-1.0.3.jar"
                          "./lib/hadoop-gpl-compression-0.2.0-dev.jar"
                          "./lib/hadoop-snappy-0.0.1-SNAPSHOT.jar"
                          "./lib/hamcrest-core-1.1.jar"
                          "./lib/hbase-0.94.1.jar"
                          "./lib/hbase-0.94.1-javadoc.jar"
                          "./lib/hbase-0.94.1-sources.jar"
                          "./lib/high-scale-lib-1.1.1.jar"
                          "./lib/hsqldb-1.8.0.10.jar"
                          "./lib/httpclient-4.1.2.jar"
                          "./lib/httpcore-4.1.3.jar"
                          "./lib/icu4j-3.8.jar"
                          "./lib/jackson-core-asl-1.7.1.jar"
                          "./lib/jackson-jaxrs-1.7.1.jar"
                          "./lib/jackson-mapper-asl-1.7.1.jar"
                          "./lib/jackson-xc-1.7.1.jar"
                          "./lib/jamon-runtime-2.3.1.jar"
                          "./lib/jasper-compiler-5.5.23.jar"
                          "./lib/jasper-runtime-5.5.23.jar"
                          "./lib/jaxb-api-2.1.jar"
                          "./lib/jaxb-impl-2.2.3-1.jar"
                          "./lib/jempbox-0.2.0.jar"
                          "./lib/jersey-core-1.8.jar"
                          "./lib/jersey-json-1.8.jar"
                          "./lib/jersey-server-1.8.jar"
                          "./lib/jets3t-0.7.1.jar"
                          "./lib/jettison-1.1.jar"
                          "./lib/jetty-6.1.26.jar"
                          "./lib/jetty-util-6.1.26.jar"
                          "./lib/jruby-complete-1.6.5.jar"
                          "./lib/jsp-2.1-6.1.14.jar"
                          "./lib/jsp-api-2.1-6.1.14.jar"
                          "./lib/jsr305-1.3.9.jar"
                          "./lib/junit-4.10.jar"
                          "./lib/junit-4.10-javadoc.jar"
                          "./lib/junit-4.10-sources.jar"
                          "./lib/kfs-0.3.jar"
                          "./lib/libthrift-0.8.0.jar"
                          "./lib/log4j-1.2.16.jar"
                          "./lib/metrics-core-2.1.2.jar"
                          "./lib/nekohtml-1.9.9.jar"
                          "./lib/netty-3.2.4.Final.jar"
                          "./lib/ooxml-schemas-1.0.jar"
                          "./lib/oro-2.0.8.jar"
                          "./lib/pdfbox-0.7.3.jar"
                          "./lib/poi-3.5-beta5.jar"
                          "./lib/poi-ooxml-3.5-beta5.jar"
                          "./lib/poi-scratchpad-3.5-beta5.jar"
                          "./lib/protobuf-java-2.4.0a.jar"
                          "./lib/servlet-api-2.5-20081211.jar"
                          "./lib/servlet-api-2.5-6.1.14.jar"
                          "./lib/slf4j-api-1.4.3.jar"
                          "./lib/slf4j-log4j12-1.4.3.jar"
                          "./lib/snappy-java-1.0.3.2.jar"
                          "./lib/spider_common-0.0.1-SNAPSHOT.jar"
                          ;; "./lib/spider_common-SNAPSHOT.jar"
			  ;; "./lib/spider_common-0.0.1-SNAPSHOT-jar-with-dependencies.jar"
                          "./lib/stax-api-1.0.1.jar"
                          "./lib/stax-api-1.0-2.jar"
                          "./lib/tika-0.3.jar"
                          "./lib/velocity-1.7.jar"
                          "./lib/xercesImpl-2.8.1.jar"
                          "./lib/xml-apis-1.3.03.jar"
                          "./lib/xmlbeans-2.3.0.jar"
                          "./lib/xmlenc-0.52.jar"
                          "./lib/zookeeper-3.4.3.jar"
                          ))
 ;; You can set different user name and e-mail address for each project
 
 )

(setq jdibug-connect-host "localhost"
      jdibug-connect-port 6001)

(message "loaded prj.el")
;; just a test line
